name: Build DemoApp Infrastructure Artifact
on:
  push:
    branches: [working]
  workflow_dispatch:
    
env:
  pathToMainBicep: ./infra/main.bicep
  pathToParamsFile: ./infra/main.params.json
  pathToBuildArtifact: ./infra/build.json

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: 'Checkout Working Branch'
      uses: actions/checkout@v1

    - name: Print User
      run: echo "${{ GITHUB_ACTOR }}"
      
    - name: 'Login into Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        enable-AzPsSession: true

    - name: 'Run Test Build of Bicep Files'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          az config set bicep.use_binary_from_path=False
          az bicep build --file ${{ env.pathToMainBicep }} --outfile ${{ env.pathToBuildArtifact }}
        azPSVersion: "latest"

  Deploy:
    runs-on: windows-latest
    needs: [Build]
    steps:
    - name: 'Login into Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        enable-AzPsSession: true

    - name: 'Deploy Demo Environment'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $WarningPreference = 'SilentlyContinue'
          $azContext = $(Set-AzContext -SubscriptionId '197f4130-ef26-4439-a354-eb5a2a2d7f85')
          $grafanaId = ($azContext.Account.ExtendedProperties.HomeAccountId.Split('.')[0])
          $deployment = New-AzSubscriptionDeployment `
            -Name 'dashboardDemo' `
            -location 'eastus' `
            -TemplateFile ${{ env.pathToMainBicep }} `
            -TemplateParameterFile ${{ env.pathToParamsFile }} `
            -deployedBy "${{ GITHUB_ACTOR }}" `
            -grafanaAADId $grafanaId
        azPSVersion: "latest"