name: Build DemoApp Infrastructure Artifact
on:
  push:
    branches: [working]
  workflow_dispatch:

## Please update these to reflect your requrired Demo Deployment ##  
env:
  demoSubscriptionId: '197f4130-ef26-4439-a354-eb5a2a2d7f85'
  demoLocation: 'eastus'
  demoDeploymentName: 'dashboardDemo'



jobs:
  Test:
    name: Test Infrastructure (Bicep)
    runs-on: windows-latest
    steps:
    - name: 'Checkout Working Branch'
      uses: actions/checkout@v1
      
    - name: 'Login into Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        enable-AzPsSession: true

    - name: 'Run Test Build of Bicep Files'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          az config set bicep.use_binary_from_path=False
          az bicep build --file ./infra/main.bicep --outfile ./infra/build.json
        azPSVersion: "latest"

  Deploy:
    name: Deploy Infrastructure (Bicep)
    runs-on: windows-latest
    needs: [Test]
    steps:
    - name: 'Checkout Working Branch'
      uses: actions/checkout@v1

    - name: 'Login into Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        enable-AzPsSession: true

    - name: 'Deploy Demo Environment'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $WarningPreference = 'SilentlyContinue'
          [void](Set-AzContext -SubscriptionId ${{ env.demoSubscriptionId }})
          $deployment = New-AzSubscriptionDeployment `
            -Name '${{ env.demoDeploymentName }}' `
            -location '${{ env.demoLocation }}' `
            -TemplateFile ./infra/main.bicep `
            -TemplateParameterFile ./infra/main.params.json `
            -deployedBy "${{ github.actor }}" 
        azPSVersion: "latest"