name: Build DemoApp Infrastructure
on:
  push:
    branches: [working]
  workflow_dispatch:

## Please update these to reflect your requrired Demo Deployment ##  
env:
  demoSubscriptionId: '197f4130-ef26-4439-a354-eb5a2a2d7f85'
  demoLocation: 'eastus'
  demoDeploymentName: 'grafanaDemo'

jobs:
  TestDeploy:
    name: Test Bicep Deployment Files
    runs-on: windows-latest
    steps:
    - name: 'Checkout Working Branch'
      uses: actions/checkout@v1

    - name: 'Login into Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        enable-AzPsSession: true

    - name: 'Test ARM Template via WhatIf'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $WarningPreference = 'SilentlyContinue'
          [void](Set-AzContext -SubscriptionId ${{ env.demoSubscriptionId }})
          (New-Item ((new-object system.io.directoryinfo $pwd).parent.fullname + '\webTest\webTestPrimaryRegion.xml'))
          (New-Item ((new-object system.io.directoryinfo $pwd).parent.fullname + '\webTest\webTestSecondaryRegion.xml'))
          $deployment = New-AzSubscriptionDeployment `
            -Name '${{ env.demoDeploymentName }}' `
            -location '${{ env.demoLocation }}' `
            -TemplateFile ./infra/main.bicep `
            -TemplateParameterFile ./infra/main.params.json `
            -deployedBy "${{ github.actor }}" `
            -WhatIf
        azPSVersion: "latest"

  RunScript:
    name: Deploy Demo Environment 
    runs-on: windows-latest
    needs: [TestDeploy]
    steps:
    - name: 'Checkout Working Branch'
      uses: actions/checkout@v1

    - name: 'Login into Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        enable-AzPsSession: true

    - name: 'Execute Deploy.ps1 Script'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $WarningPreference = 'SilentlyContinue'
          [void](Set-AzContext -SubscriptionId ${{ env.demoSubscriptionId }})
          Set-Location .\code\scripts\
           (./deploy.ps1 -deployedBy '${{ github.actor }}' -InformationAction Continue) 
        azPSVersion: "latest"