name: Build DemoApp Infrastructure
on:
  push:
    branches: [working]
  workflow_dispatch:

## Please update these to reflect your requrired Demo Deployment ##  
env:
  demoSubscriptionId: '197f4130-ef26-4439-a354-eb5a2a2d7f85'
  demoLocation: 'eastus'
  demoDeploymentName: 'grafanaDemo'

jobs:
  TestBicep:
    name: Test Bicep for Errors
    runs-on: windows-latest
    steps:
    - name: 'Checkout Working Branch'
      uses: actions/checkout@v1

    - name: 'Run Test Build of Bicep Files'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          az config set bicep.use_binary_from_path=False
          az bicep build --file ./infra/main.bicep --outfile ./infra/build.json
        azPSVersion: "latest"

  RunScript:
    name: Deploy Demo Environment 
    runs-on: windows-latest
    needs: [TestBicep]
    steps:
    - name: 'Checkout Working Branch'
      uses: actions/checkout@v1

    - name: 'Login into Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        enable-AzPsSession: true

    - name: 'Execute Deploy.ps1 Script'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $WarningPreference = 'SilentlyContinue'
          [void](Set-AzContext -SubscriptionId ${{ env.demoSubscriptionId }})
          Set-Location .\code\scripts\
           (./deploy.ps1 -deployedBy '${{ github.actor }}' -InformationAction Continue) 
        azPSVersion: "latest"